version: "3.9"
services:
  wordpress-site:
    image: wordpress:php8.0
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://aiclub.uit.edu.vn');
        define('WP_SITEURL', 'https://aiclub.uit.edu.vn');
    volumes:
      - wordpress-site:/var/www/html
    depends_on:
      - wordpress-db

  wordpress-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - wordpress-db:/var/lib/mysql

volumes:
  wordpress-db:
  wordpress-site:
